# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Upgrade pip and install hatchling to build the project
RUN pip install --upgrade pip && \
    pip install hatchling

WORKDIR /app

# Copy the project files
COPY . /app

# Install project dependencies and the MCP server
RUN pip install --no-cache-dir .

# Expose any port if needed (MCP uses stdio by default, so not needed)

# Command to run the MCP server
CMD ["mcp-server-ipinfo"]
